version: "3.8"

services:
  db:
    image: postgres:12.2-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bancaire
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data